[package]
name = "rust_resource_timeline"
version = "0.1.0"
authors = ["Gabriel Luo <luogm@umich.edu>"]
edition = "2018"

[lib]
name = "data"
path = "src/lib.rs"

[[example]]
name = "simple"
path = "example/simple_lifetime/main.rs"

[dependencies]
resvg = "0.9.0"
# rrt_lib = { path = "./" }
