[package]
name = "rrt"
version = "0.1.0"
authors = ["Gabriel Luo <luogm@umich.edu>", "Ke Du <madoka@umich.edu>", "Yingying Zhu <zyy@umich.edu>"]
edition = "2018"

[lib]
name = "rrt_lib"
path = "src/lib.rs"

[[example]]
name = "default"
path = "examples/move_with_no_borrow/main.rs"

[dependencies]
handlebars = "3.0.1"
serde = { version = "1.0", features = ["derive"] }
# rrt_lib = { path = "./" }
