theme: jekyll-theme-midnight
title: Lifetime Visualizer for Rust
description: The Lifetime Tutorial from Rust The Book supplemented with the visualization using a line-diagram.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md